[package]
name = "rsdis"
version = "0.1.0"
authors = ["Michał Wawrzynowicz <michalwa2003@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serenity = "0.9.1"
toml = "0.5.8"
mongodb = "1.1.1"
